/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetoweka.view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import projetoweka.controller.DadosController;

/**
 *
 * @author farofa
 */
public class BuscaArquivoDados extends javax.swing.JFrame {
    private DadosController mainController;

    /**
     * Creates new form BuscaArquivo
     */
    public BuscaArquivoDados() {
        initComponents();
	
        this.setLocationRelativeTo(null);
        
        this.mainController = new DadosController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        janelaProcura = new javax.swing.JFileChooser();
        textoArquivo = new javax.swing.JTextField();
        botaoBuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        botaoIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Arquivo de Dados");

        textoArquivo.setText("./arquivos/harrypotter.arff");

        botaoBuscar.setText("Buscar");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });

        botaoIniciar.setText("Importar");
        botaoIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIniciarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoIniciar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoBuscar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        FileNameExtensionFilter filter = new FileNameExtensionFilter("ARFF", "arff");
        
        janelaProcura.setFileFilter(filter);
        janelaProcura.setVisible(true);  

        int result = janelaProcura.showOpenDialog(null); 

        if(result == JFileChooser.OPEN_DIALOG)
                textoArquivo.setText(janelaProcura.getSelectedFile().toString());
    }//GEN-LAST:event_botaoBuscarActionPerformed

    private void botaoIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIniciarActionPerformed
        try {    
            mainController.setDados(textoArquivo.getText());
        
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                                            this, 
                                            "Erro ao abrir o arquivo de dados"+
                                                    "\nErro: "+ex.getMessage()+
                                                    "\nCausa: "+ex.getCause(), 
                                            "Erro", 
                                            JOptionPane.INFORMATION_MESSAGE, 
                                            new ImageIcon("img/error-circle.png")
                                        );
        }
    }//GEN-LAST:event_botaoIniciarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoIniciar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFileChooser janelaProcura;
    private javax.swing.JTextField textoArquivo;
    // End of variables declaration//GEN-END:variables
}
