/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetoweka.view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import projetoweka.controller.MainController;

/**
 *
 * @author farofa
 */
public class ConfiguracoesArvoreDeDecisao extends javax.swing.JFrame {
    private MainController controller;

    /**
     * Creates new form ConfiguracoesArvoreDeDecisao
     */
    public ConfiguracoesArvoreDeDecisao(MainController controller) {
        this.controller = controller;
        
        initComponents();
	
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkAvaliacaoNormal = new javax.swing.JCheckBox();
        checkAvaliacaoCruzada = new javax.swing.JCheckBox();
        labelFolds = new javax.swing.JLabel();
        textoFolds = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        textoParametros = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        botaoGerarRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configurações da Árvore de Decisão");

        checkAvaliacaoNormal.setText("Avaliação Normal");

        checkAvaliacaoCruzada.setText("Avaliação Cruzada");
        checkAvaliacaoCruzada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkAvaliacaoCruzadaMouseClicked(evt);
            }
        });

        labelFolds.setText("Folds");
        labelFolds.setEnabled(false);

        textoFolds.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        textoFolds.setEnabled(false);

        jLabel1.setText("Parâmetros (separe cada um por \"|\")");

        botaoGerarRelatorio.setText("Gerar Relatório");
        botaoGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGerarRelatorioActionPerformed(evt);
            }
        });
        jPanel1.add(botaoGerarRelatorio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoParametros)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkAvaliacaoNormal)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkAvaliacaoCruzada)
                                .addGap(18, 18, 18)
                                .addComponent(labelFolds)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoFolds, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkAvaliacaoNormal)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkAvaliacaoCruzada)
                    .addComponent(labelFolds)
                    .addComponent(textoFolds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoParametros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkAvaliacaoCruzadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkAvaliacaoCruzadaMouseClicked
        if(checkAvaliacaoCruzada.isSelected()) {
            labelFolds.setEnabled(true);
            textoFolds.setEnabled(true);
            textoFolds.setText("2");
        }
        else {
            labelFolds.setEnabled(false);
            textoFolds.setEnabled(false);
            textoFolds.setText(null);
        }
    }//GEN-LAST:event_checkAvaliacaoCruzadaMouseClicked

    private void botaoGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerarRelatorioActionPerformed
        try
        {
            boolean avaliacaoNormal = checkAvaliacaoNormal.isSelected();
            boolean avaliacaoCruzada = checkAvaliacaoCruzada.isSelected();
            String[] options = null;
            
            if(!textoParametros.getText().isEmpty())
            {
                String parametros = textoParametros.getText();
                options = parametros.split("\\|");
            }

            int folds = -1;

            if(avaliacaoCruzada == true)
            {
                folds = Integer.parseInt(textoFolds.getText());
            }
            
            if(avaliacaoCruzada == true && folds < 2)
            {
                JOptionPane.showMessageDialog(
                                            this, 
                                            "O campo Folds deve ser maior do que 1",
                                            "Erro", 
                                            JOptionPane.INFORMATION_MESSAGE, 
                                            new ImageIcon("img/error-circle.png")
                                        );
                textoFolds.requestFocus();
            }
            else
            {
                String relatorio;
                relatorio = controller.imprimeArvoreDeDecisao(avaliacaoNormal, avaliacaoCruzada, folds, options);

                new Relatorios("Árvore de Decisão", relatorio).setVisible(true);
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(
                                            this, 
                                            "Erro ao abrir o arquivo de dados"+
                                                    "\nErro: "+ex.getMessage()+
                                                    "\nCausa: "+ex.getCause(), 
                                            "Erro", 
                                            JOptionPane.INFORMATION_MESSAGE, 
                                            new ImageIcon("img/error-circle.png")
                                        );
        }
    }//GEN-LAST:event_botaoGerarRelatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoGerarRelatorio;
    private javax.swing.JCheckBox checkAvaliacaoCruzada;
    private javax.swing.JCheckBox checkAvaliacaoNormal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelFolds;
    private javax.swing.JFormattedTextField textoFolds;
    private javax.swing.JTextField textoParametros;
    // End of variables declaration//GEN-END:variables
}
