/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetoweka.view;

import projetoweka.controller.MainController;

/**
 *
 * @author farofa
 */
public class Principal extends javax.swing.JFrame {
    private MainController controller;
    
    /**
     * Creates new form Principal
     */
    public Principal(MainController controller) {
        this.controller = controller;
        
        initComponents();
	
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuRelatorios = new javax.swing.JMenu();
        menuRelatoriosDados = new javax.swing.JMenuItem();
        menuRelatoriosArvoreDeDecisao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuRelatorios.setText("Relatórios");

        menuRelatoriosDados.setText("Dados");
        menuRelatoriosDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatoriosDadosActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuRelatoriosDados);

        menuRelatoriosArvoreDeDecisao.setText("Árvore de Decisão (J48)");
        menuRelatoriosArvoreDeDecisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatoriosArvoreDeDecisaoActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuRelatoriosArvoreDeDecisao);

        jMenuBar1.add(menuRelatorios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuRelatoriosDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatoriosDadosActionPerformed
        String relatorio = controller.imprimeDados();
        
        new Relatorios("Dados Inicial", relatorio).setVisible(true);
    }//GEN-LAST:event_menuRelatoriosDadosActionPerformed

    private void menuRelatoriosArvoreDeDecisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatoriosArvoreDeDecisaoActionPerformed
        new ConfiguracoesArvoreDeDecisao(controller).setVisible(true);
    }//GEN-LAST:event_menuRelatoriosArvoreDeDecisaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenuItem menuRelatoriosArvoreDeDecisao;
    private javax.swing.JMenuItem menuRelatoriosDados;
    // End of variables declaration//GEN-END:variables
}
