/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetoweka.view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import projetoweka.controller.DadosController;
import projetoweka.controller.PerguntasController;
import projetoweka.model.Perguntas;

/**
 *
 * @author farofa
 */
public class Quiz extends javax.swing.JFrame {
    private DadosController dadosController;
    private PerguntasController perguntasController;
    private int perguntaIndex;
    private int[] respostas;

    /**
     * Creates new form Quiz
     */
    public Quiz() {
        initComponents();
	
        this.setLocationRelativeTo(null);
        
        dadosController = new DadosController();
        perguntasController = new PerguntasController();
        perguntaIndex = 0;
        respostas = new int[perguntasController.getPerguntas().size()];
        
        this.refreshDados();
    }
    
    private void refreshDados()
    {
        Perguntas pergunta = perguntasController.getPerguntas().get(perguntaIndex);
        
        this.setTitle("Pergunta "+(perguntaIndex+1)+": "+pergunta.getPergunta());
        labelPergunta.setText(pergunta.getPergunta());
        comboAlternativas.removeAllItems();
            comboAlternativas.addItem("");
        for(String alternativa : pergunta.getAlternativas())
            comboAlternativas.addItem(alternativa);
        
        atualizaBotoes();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPergunta = new javax.swing.JLabel();
        comboAlternativas = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        botaoVoltar = new javax.swing.JToggleButton();
        botaoAvancar = new javax.swing.JButton();
        botaoFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quiz:");

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoVoltar);

        botaoAvancar.setText("Avançar");
        botaoAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAvancarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoAvancar);

        botaoFinalizar.setText("Finalizar");
        botaoFinalizar.setEnabled(false);
        botaoFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFinalizarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoFinalizar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPergunta)
                            .addComponent(comboAlternativas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(labelPergunta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboAlternativas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAvancarActionPerformed
        if(isRespostaCorrect()) {
            perguntaIndex++;
            refreshDados();
        }
    }//GEN-LAST:event_botaoAvancarActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        perguntaIndex--;
        refreshDados();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFinalizarActionPerformed
        try {
            if(isRespostaCorrect()) {
                String resposta = dadosController.classifica(respostas);
                
                JOptionPane.showMessageDialog(
                                            this, 
                                            "Sua casa é: "+resposta, 
                                            "Resposta", 
                                            JOptionPane.INFORMATION_MESSAGE, 
                                            new ImageIcon("img/success-circle.png")
                                        );
                
                this.dispose();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                                            this, 
                                            "Erro ao classificar dados"+
                                                    "\nErro: "+ex.getMessage()+
                                                    "\nCausa: "+ex.getCause(), 
                                            "Erro", 
                                            JOptionPane.INFORMATION_MESSAGE, 
                                            new ImageIcon("img/error-circle.png")
                                        );
        }
    }//GEN-LAST:event_botaoFinalizarActionPerformed

    private void atualizaBotoes()
    {
        if(perguntaIndex == 0)
            botaoVoltar.setEnabled(false);
        else
            botaoVoltar.setEnabled(true);
        
        if(perguntaIndex < (perguntasController.getPerguntas().size() - 1)) {
            botaoAvancar.setEnabled(true);
            botaoFinalizar.setEnabled(false);
        }
        else {
            botaoAvancar.setEnabled(false);
            botaoFinalizar.setEnabled(true);
        }
    }
    
    private boolean isRespostaCorrect()
    {
        int resposta = comboAlternativas.getSelectedIndex();
        
        if(resposta > 0) {
            respostas[perguntaIndex] = resposta;
            
            return true;
        }
        else {
            JOptionPane.showMessageDialog(
                                            this, 
                                            "Selecione uma opção", 
                                            "Alerta", 
                                            JOptionPane.INFORMATION_MESSAGE, 
                                            new ImageIcon("img/alert-circle.png")
                                        );
            
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAvancar;
    private javax.swing.JButton botaoFinalizar;
    private javax.swing.JToggleButton botaoVoltar;
    private javax.swing.JComboBox<String> comboAlternativas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelPergunta;
    // End of variables declaration//GEN-END:variables
}
